### ISSUE TITLE
怎么安装拓展到TS+

### ISSUE THREAD

**Issue by sucof** [slimkit/plus-component-news#1]
按照如下命令安装
composer require zhiyicx/plus-component-news
php artisan component install zhiyicx/plus-component-news，
有提示plus-install-plugin已经废弃了，安装好后，显示还是有很多错误？

**Comment by this-BaiShi** [comment]
plus-install-plugin 是之后准备废弃的安装依赖，之后会做处理
请问安装后还显示了什么错误呢？

**Comment by sucof** [comment]
news模块的一些图标不显示（这个应该是大大没有防止ico.png图片），选择banner图有401权限错误等问题，还有就是使用npm run dev，无法看到前台的界面，请问，有更相信的安装步骤吗？刚学习laravel，问的比较初级。。。

**Comment by this-BaiShi** [comment]
news模块的icon确实还没准备，然后banner图401问题可以看一下是否有上传附件相关权限
资讯模块的话，只有提供给客户端的接口和后台。

**Comment by sucof** [comment]
@this-BaiShi ，是现在的资讯模块前台不能在浏览器显示吗？若不支持，以后会支持吗？

**Comment by this-BaiShi** [comment]
是这样的，我们开发了pc扩展包去展示动态以及资讯模块的数据，不过这个包是公司的私库

**Comment by lain1936** [comment]
composer require zhiyicx/plus-component-news
php artisan package:handle news install
php artisan vendor:publish --force

我是手动这样安装的 

有几个问题
1. 上传图片走的是 /api/v1/storages/task ，提示“用户认证失败”，无法上传图片
请求的Cookie是有XSRF-TOKEN 和 plus_session

2.v1的api会全面换成v2吗，因为v2和v1好像都有用户注册已经验证码，有点重合啊

3.还有个plus-component-feed后端展示目前好像用的react, 有计划统一前端的框架吗？还是说现在着重于在后端，前端的话只是主体是vue？

**Comment by this-BaiShi** [comment]
1. 接口方面 v1会逐步替换为v2，v1和v2最主要的区别在于严格遵循reset，客户端需要根据Http Status去解析数据体，而不是像v1在数据体里根据后端约定的状态码进行解析。客户端会暂时兼容v1，有同样功能的v2接口优先使用v2，这块我们会根据需求去重构或者新增v2接口
2.feed扩展包的后台正在重构，在设计之初是想让扩展包开发者自由选择后台开发方式，后来发现各个扩展包的后台风格差异过大，所以feed包后台这块正在用vue进行重构
