### ISSUE TITLE
封面图片不能上传

### ISSUE THREAD

**Issue by 1459416736** [slimkit/plus-component-news#5]
在后台进行封面图片上传不成功？
一直提示：没有上传封面图片

**Comment by this-BaiShi** [comment]
最近资讯模块新增了部分功能，后台还没有跟进开发

**Comment by lain1936** [comment]
好像是要文件上传 需要用到token来获取用户（auth.api的中间件），需要走tokens接口去先获得jwt的token，不过首次获取需要用户名和密码， 最好在登录后后台时候，记录在数据库或者前端，管理扩展时候，页面取得 旧token，js刷新得到新的token
