### ISSUE TITLE
资讯发布的时候3处错误

### ISSUE THREAD

**Issue by 1459416736** [slimkit/plus-component-news#8]
1.this.$refs.modelTips.clear   报clear() 方法 未定义
2.this.$refs.modelTips.show   报show   () 方法 未定义
3.content 发布内容不能获取

**Comment by this-BaiShi** [comment]
最新的扩展包吗，如果不是，请先使用github源的composer包，最近后台一直在加功能和修复已知问题

**Comment by 1459416736** [comment]
是的，我采用的是最新的，今天才从github源下载的

**Comment by this-BaiShi** [comment]
好的，这块我会跟相关人员反馈
